AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  picture4You:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: picture4You/lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::966887599552:role/ilab-bot-functions'
      Environment:
        Variables:
          BingImageAPISubscriptionKey: fdaa42297d2a4e2296aa728bb3d93d5a
          BingImageAPIHost: api.cognitive.microsoft.com
          BingImageAPIURL: /bing/v7.0/images/search
